version: "3.9"
services:
  hello-world:
    depends_on:
      database:
        condition: service_healthy
    build: ..
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      DB_HOST: database
  database:
    image: "mysql:8.0"
    healthcheck:
      test: "ls /var/run/mysqld/mysqld.sock"
      interval: 5s
    hostname: database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: default
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes: [./setup.sql:/docker-entrypoint-initdb.d/setup.sql]