apiVersion: v2
name: chart
description: A dummy Hello World app

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.2.0