name: Build and deploy Hello World app

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  NEW_IMAGE: "gggal/hello-world-app:${{ github.ref_name }}"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push new artifact to registry
      run: |
        docker build . -t $NEW_IMAGE
        docker push $NEW_IMAGE
    # - name: Install Kubectl
    #   uses: azure/setup-kubectl@v2.0
    # - name: Configure Kubectl
    #   uses: Azure/k8s-set-context@v2
    #   with:
    #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
    # - name: Deploy to K8s
    #   env:
    #   - DEPLOYMENT_NAME=hello-world
    #   run: |
    #     kubectl get deployment $DEPLOYMENT_NAME >/dev/null 2>&1
    #     if [ $? -ne 0 ]; then
    #       kubectl create deploy $DEPLOYMENT_NAME --image $NEW_IMAGE --port=8000
    #     else
    #       kubectl set image deployment/$DEPLOYMENT_NAME hello-world-app=$NEW_IMAGE
    #     fi